version: 2
jobs:
  build:
    docker:
      # Specify the Python version you desire here
      - image: circleci/python:3.6.4-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test


    working_directory: ~/identity-analytics-etl

    steps:
      - checkout

      - restore_cache:
         keys:
           - identity-analytics-etl-{{ checksum "requirements.txt" }}

      - run:
         name: create virtualenv and install python dependencies
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt

      - run:
          name: tests
          command: |
            . venv/bin/activate
            python tests/test.py

      - run:
         name: coverage report
         command: |
          . venv/bin/activate
          py.test --cov=src tests/
