version: 2
jobs:
  build:
    working_directory: ~/identity-analytics-etl
    docker:
      # Specify the Python version you desire here
      # TODO: figure out a better way to setup postgres see below 
      # https://discuss.circleci.com/t/rails-app-cant-connect-to-postgres-server/13059/3
      - image: circleci/python:3.6.4
        environment:
          PGHOST: 127.0.0.1
          PGUSER: circle
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circle
          POSTGRES_DB: dev
          POSTGRES_PASSWORD: ""


    steps:
      - checkout

      - restore_cache:
         keys:
           - identity-analytics-etl-{{ checksum "requirements.txt" }}

      - run:
         name: create virtualenv and install python dependencies
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt

      - run:
          name: tests
          command: |
            . venv/bin/activate
            python tests/test.py

      - run:
         name: coverage report
         command: |
          . venv/bin/activate
          py.test --cov=src tests/
